{% set name = "snowpark-connect-deps-1" %}
{% set version = "3.56.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 24d38e2fd732802705ceff6c5ba5bf766a70dd8e6231ab4f96c099dc3569d6ad

build:
  number: 100
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310 or py>312]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - snowpark_connect_deps_1
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/snowpark-connect-deps-1
  summary: Spark JAR dependencies for Snowpark Connect (Part 1)
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-binary
    - NOTICE-binary
    - LICENSE.txt
  description: |
    Spark framework JAR files for Snowpark Connect. This package contains Apache Spark 3.5.6 core components.
  doc_url: https://pypi.org/project/snowpark-connect-deps-1
  dev_url: https://pypi.org/project/snowpark-connect-deps-1

extra:
  recipe-maintainers:
    - snegireff
